"""Reaction model init migration

Revision ID: 23974a09069c
Revises: f8b727d7f906
Create Date: 2026-05-06 15:00:29.170402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "23974a09069c"
down_revision: Union[str, Sequence[str], None] = "f8b727d7f906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_reactions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("reaction", sa.Boolean(), nullable=True),
        sa.Column("comment", sa.String(length=1023), nullable=True),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.CheckConstraint("grade BETWEEN 1 AND 10", name="ck_grade_range"),
        sa.CheckConstraint(
            "reaction IS NOT NULL OR comment IS NOT NULL OR grade IS NOT NULL",
            name="ck_reaction_or_comment_or_grade",
        ),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "movie_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_reactions")
    # ### end Alembic commands ###
