"""CommentAnswer migration init

Revision ID: 668f328c3776
Revises: e8a8fe18d81f
Create Date: 2026-05-08 11:58:28.140605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "668f328c3776"
down_revision: Union[str, Sequence[str], None] = "e8a8fe18d81f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_answers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_reaction_user_id", sa.Integer(), nullable=False),
        sa.Column("movie_reaction_movie_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=1023), nullable=True),
        sa.Column("reaction", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "comment IS NOT NULL OR reaction IS NOT NULL", name="ck_reaction_or_comment"
        ),
        sa.ForeignKeyConstraint(
            ["movie_reaction_user_id", "movie_reaction_movie_id"],
            ["movie_reactions.user_id", "movie_reactions.movie_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "user_id", "movie_reaction_user_id", "movie_reaction_movie_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_answers")
    # ### end Alembic commands ###
