"""empty message

Revision ID: af17d893070f
Revises: 59a4b0f69c71
Create Date: 2026-05-02 11:18:02.538137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af17d893070f'
down_revision: Union[str, Sequence[str], None] = '59a4b0f69c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certifications', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=31),
               existing_nullable=False)
    op.create_unique_constraint(None, 'genres', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    op.alter_column('certifications', 'name',
               existing_type=sa.String(length=31),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
