"""add nullable to certification field

Revision ID: f8b727d7f906
Revises: af17d893070f
Create Date: 2026-05-02 17:04:07.092604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b727d7f906'
down_revision: Union[str, Sequence[str], None] = 'af17d893070f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'certification_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'certification_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
