"""add field expired_at to refresh token model

Revision ID: fc2dd8570db8
Revises: 6ba6ef6057f9
Create Date: 2026-04-28 14:07:02.262824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc2dd8570db8"
down_revision: Union[str, Sequence[str], None] = "6ba6ef6057f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "expires_at")
    # ### end Alembic commands ###
